config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  post '/charge_categories', to: 'chargecategories#create'

  # resources :users, only: [:new, :create, :show]
  # resources :charges

  namespace :admin do
    resources :budgets, only: [:index]
    resources :users, only: [:index]
  end

  resources :users, only: [:new, :create, :show] do
    resources :budgets, only: [:index, :show, :new, :create, :edit, :update] do
      resources :charges
      resources :categories, only: [:new, :create, :index]
    end
  end

  resources :adjustments, only: [:create]
end

app/models/budget.rb
class Budget < ApplicationRecord
  validates :name, presence: true

  has_many :categories, dependent: :destroy
  has_many :charges, dependent: :destroy
  belongs_to :user

  after_create :add_to_be_budgeted

  def available_to_budget
    categories.find_by(title: "To be budgeted").balance
  end

  private

  def add_to_be_budgeted
    categories.create(title: "To be budgeted")
  end
end

app/controllers/admin/budgets_controller.rb
#
class Admin::BudgetsController < Admin::BaseController
  def index
    @budgets = Budget.all
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @budgets = @user.budgets
  end

  def show
    @user = User.find(params[:user_id])
    @budget = Budget.find(params[:id])
    @adjustment = Adjustment.new
  end

  def new
    @user = User.find(params[:user_id])
    @budget = @user.budgets.new
  end

  def create
    user = User.find(params[:user_id])
    @budget = user.budgets.new(budget_params)
    if @budget.save
      flash[:success] = "#{@budget.name} added!"
      redirect_to user_budgets_path(user)
    else
      flash[:error] = "Budget wasn't created successfully"
      @user = User.find(params[:user_id])
      render :new
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @budget = Budget.find(params[:id])
  end

  def update
    user = User.find(params[:user_id])
    @budget = Budget.find(params[:id])
    @budget.update(budget_params)
    if @budget.save
      flash[:success] = 'Budget updated!'
      redirect_to user_budgets_path(user)
    else
      render :edit
    end
  end
  #
  # def destroy
  #   transaction = Transaction.find(params[:id])
  #   transaction.destroy
  #
  #   flash[:success] = "Transaction from #{transaction.date} successfully deleted!"
  #   redirect_to transactions_path
  # end


  private

  def budget_params
    params.require(:budget).permit(:name)
  end
end

app/views/budgets/_form.html.erb
<%= form_for [@user, @budget] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/budgets/edit.html.erb
<% if current_user.id == @budget.user.id || current_admin? %>
  <%= render partial: "form" %>
<% end %>

app/views/budgets/index.html.erb
<% if current_user.id == @user.id || current_admin? %>
  <div class="row">
    <% @budgets.each do |budget| %>
    <div class="col-sm-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= budget.name %> budget</h5>
          <p class="card-text">There are <%= budget.categories.count %> categories in this budget: <%= budget.categories.map(&:title).join(", ") %></p>
          <a href="/users/<%= @user.id%>/budgets/<%= budget.id %>" class="btn btn-primary">Go to <%= budget.name %> budget</a>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <%= link_to "Create a new budget", new_user_budget_path(@user) %>
<% end %>

app/views/budgets/new.html.erb
<% if current_user.id == @user.id || current_admin? %>
  <%= render partial: "form" %>
<% end %>

app/views/budgets/show.html.erb
<% if current_user.id == @budget.user.id || current_admin? %>
  <h1>Budget: <%= @budget.name %></h1>
  <div class="col-sm-4">
    <div class="card">
      <h5 class="card-header">Available to be Budgeted</h5>
      <div class="card-body">
        <h5 class="card-title"><%= number_to_currency(@budget.available_to_budget) %> Available</h5>
      </div>
    </div>
  </div>
  <a href="<%= new_user_budget_category_path(@user, @budget)%>" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Create a new category</a>
  <a href="<%= edit_user_budget_path(@user, @budget)%>" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Edit Budget</a>
  <a href="<%= user_budget_charges_path(@user, @budget)%>" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Budget Charges</a>

    <div class="row">
      <% @budget.categories.each do |category| %>
      <% next if category.title == "To be budgeted" %>
      <div class="col-sm-4">
        <div class="card <%= category.title%>">
          <h5 class="card-header"><%= category.title %></h5>
          <div class="card-body">
            <h5 class="card-title"><%= number_to_currency(category.balance) %> Available</h5>
            <%= form_for @adjustment , :html => {:class => "form-inline center"} do |f| %>
              <div class="form-group">
                <div class="col-md-8">
                  <%= f.number_field :amount, step: 0.01, class: "form-control" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
<% end %>