config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  post '/charge_categories', to: 'chargecategories#create'

  # resources :users, only: [:new, :create, :show]
  # resources :charges

  namespace :admin do
    resources :budgets, only: [:index]
    resources :users, only: [:index]
  end

  resources :users, only: [:new, :create, :show] do
    resources :budgets, only: [:index, :show, :new, :create, :edit, :update] do
      resources :charges
      resources :categories, only: [:new, :create, :index]
    end
  end

  resources :adjustments, only: [:create]
end

app/models/charge.rb
class Charge < ApplicationRecord
  validates :date, :payee, :amount, presence: true

  has_many :charge_category_adjustments, dependent: :destroy
  has_many :categories, through: :charge_category_adjustments
  has_many :adjustments, through: :charge_category_adjustments
  belongs_to :budget

  def self.order_by_date
    order(date: :desc)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @budget = Budget.find(params[:budget_id])
    @categories = @budget.categories
    @charges = @budget.charges.order_by_date
    @charge = Charge.new
  end

  def new
    @user = User.find(params[:user_id])
    @budget = Budget.find(params[:budget_id])
    @charge = Charge.new
    # @charge_category_adjustment = ChargeCategoryAdjustment.new
    @adjustment = Adjustment.new
    @categories = @budget.categories
  end

  def create
    @user = User.find(params[:user_id])
    budget = Budget.find(params[:budget_id])
    @charge = budget.charges.new(charge_params)
    if @charge.save
      if params[:adjustments]
        build_adjustments(params[:adjustments], @charge)
      else
        adjustment = Adjustment.create!(amount: @charge.amount)
        ChargeCategoryAdjustment.create!(charge_id: @charge.id, category_id: params[:charge][:id], adjustment_id: adjustment.id)
      end
      flash[:success] = 'Charge added!'
      redirect_to user_budget_charges_path(@user, budget)
    else
      flash[:error] = "Charge wasn't created successfully"
      @budget = Budget.find(params[:budget_id])
      @categories = @budget.categories
      @charges = @budget.charges.order_by_date
      render :index
    end
  end


  def edit
    @user = User.find(params[:user_id])
    @budget = Budget.find(params[:budget_id])
    @charge = Charge.find(params[:id])
  end

  def update
    user = User.find(params[:user_id])
    budget = Budget.find(params[:budget_id])
    @charge = Charge.find(params[:id])
    @charge.update(charge_params)
    if @charge.save
      flash[:success] = 'Charge updated!'
      redirect_to user_budget_charges_path(user, budget)
    else
      render :edit
    end
  end

  def destroy
    user = User.find(params[:user_id])
    budget = Budget.find(params[:budget_id])
    charge = Charge.find(params[:id])
    charge.destroy

    flash[:success] = "Charge from #{charge.date} successfully deleted!"
    redirect_to user_budget_charges_path(user, budget)
  end

  private

  def build_adjustments(params, charge)
    params.each do |category|
      next if params[category][:amount] == ''
      adjustment = Adjustment.create(amount: params[category][:amount].to_f)
      ChargeCategoryAdjustment.create(charge_id: charge.id,
                                      category_id: category.to_i,
                                      adjustment_id: adjustment.id)
    end
  end

  def charge_params
    params.require(:charge).permit(:date, :payee, :notes, :amount)
  end
end

app/views/charges/_form.html.erb
<% if current_user.id == @user.id || current_admin? %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Date</th>
        <th scope="col">Category</th>
        <th scope="col">Payee</th>
        <th scope="col">Notes</th>
        <th scope="col">Amount</th>
      </tr>
    </thead>
    <tbody>
      <%= form_for [@user, @budget, @charge] , :html => {:class => "form-inline center"} do |f| %>
      <tr>
        <th scope="row">
          <div class="form-group">
            <div class="col-md-12">
              <%= f.date_field :date, class: "form-control" %>
            </div>
          </div>
        </th>

        <td>
        </td>

        <td>
          <div class="form-group">
            <div class="col-md-8">
              <%= f.text_field :payee, class: "form-control" %>
            </div>
          </div>
        </td>

        <td>
          <div class="form-group">
            <div class="col-md-8">
              <%= f.text_field :notes, class: "form-control" %>
            </div>
          </div>
        </td>

        <td>
          <div class="form-group">
            <div class="col-md-8">
              <%= f.number_field :amount, step: 0.01, class: "form-control" %>
            </div>
          </div>
        </td>
      </tr>

    <% @categories.each do |category| %>
      <tr>
        <%= fields_for "adjustments[#{category.id}]", @adjustment do |adjustment| %>
        <th scope="row">

        </th>

        <td>
          <p><%= category.title %></p>
        </td>

        <td>
        </td>

        <td>
        </td>

        <td>
          <div class="form-group">
            <div class="col-md-8">
              <%= adjustment.number_field :amount, step: 0.01, class: "form-control" %>
            </div>
          </div>
        </td>
        <% end %>
      </tr>
    <% end %>
    <tr>
      <td>
        <%= f.submit class: "btn btn-default btn-primary" %>
        <% end %>
      </td>
    </tr>
    </tbody>
  </table>
<% end %>

app/views/charges/edit.html.erb
<% if current_user.id == @user.id || current_admin? %>
  <%= form_for [@user, @budget, @charge], :html => {:class => "form-horizontal center"} do |f| %>

  <div class="form-group">
    <%= f.label :date, "Date", class: "col-md-4 control-label" %>
    <div class="col-md-8">
      <%= f.date_field :date, class: "form-control" %>
    </div>
  </div>

    <div class="form-group">
      <%= f.label :payee, "Payee", class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= f.text_field :payee, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :notes, "Notes", class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= f.text_field :notes, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :amount, "Amount", class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= f.number_field :amount, step: 0.01, class: "form-control" %>
      </div>
    </div>

    <%= f.submit class: "btn btn-default btn-primary" %>
  <% end %>
<% end %>

app/views/charges/index.html.erb
<% if current_user.id == @user.id || current_admin? %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Date</th>
        <th scope="col">Category</th>
        <th scope="col">Payee</th>
        <th scope="col">Notes</th>
        <th scope="col">Amount</th>
        <th scope="col">Make changes</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <%= form_for [@user, @budget, @charge], :html => {:class => "form-inline center"} do |f| %>
        <th scope="row">
          <div class="form-group">
            <div class="col-md-12">
              <%= f.date_field :date, class: "form-control", :value => Time.now.strftime('%Y-%m-%d') %>
            </div>
          </div>
        </th>

        <td>
          <div class="form-group">
            <%= f.collection_select :id, @categories, :id, :title %></br>
            <!-- <%= link_to 'I need to split this charge', new_user_budget_charge_path(@user, @budget) %> -->
          </div>
        </td>

        <td>
          <div class="form-group">
            <div class="col-md-8">
              <%= f.text_field :payee, class: "form-control" %>
            </div>
          </div>
        </td>

        <td>
          <div class="form-group">
            <div class="col-md-8">
              <%= f.text_field :notes, class: "form-control" %>
            </div>
          </div>
        </td>

        <td>
          <div class="form-group">
            <div class="col-md-8">
              <%= f.number_field :amount, step: 0.01, class: "form-control" %>
            </div>
          </div>
        </td>
        <td>
          <%= f.submit class: "btn btn-default btn-primary" %>
        </td>
        <% end %>
      </tr>
      <% @charges.each do |charge| %>
      <tr class="charges">
        <td scope="row">
          <%= charge.date %>
        </td>
        <td>
          <% if charge.categories.count == 1 %>
            <%= charge.categories.first.title %>
          <% else %>
            <% charge.charge_category_adjustments.each do |cca| %>
              <%= cca.category.title %> (<%= number_to_currency(cca.adjustment.amount)%>)</br>
            <% end %>
          <% end %>
        </td>
        <td>
          <%= charge.payee %>
        </td>
        <td>
          <%= charge.notes %>
        </td>
        <td>
          <%= number_to_currency(charge.amount) %>
        </td>
        <td>
          <%= link_to "Edit", edit_user_budget_charge_path(@user, @budget, charge) %>
          <%= link_to "Delete", user_budget_charge_path(@user, @budget, charge), method: "delete" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/charges/new.html.erb
<% if current_user.id == @user.id || current_admin? %>
  <%= render partial: "form" %>
<% end %>